/*
 *  Schema to source-code converter for VL4S
 *  RW Penney, November 2017
 */

//  Copyright (C) 2017, RW Penney
//  This file is part of VL4S.
//
//  VL4S is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Foobar is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with VL4S.  If not, see <http://www.gnu.org/licenses/>.

package uk.rwpenney.vl4s.gen

import java.io.{ OutputStream, PrintWriter }
import scala.annotation.tailrec


trait TypeCoder {
  def typename: String
  def toCode: String
}


class EmptyCoder extends TypeCoder {
  def typename = "[EMPTY]"
  def toCode = ""
}


class BareCoder(defn: VLbareType) extends TypeCoder {
  def typename = CodeGen.mapBareTypes.getOrElse(defn.name, defn.name)
  def toCode = ""
}


class ArrayCoder(defn: VLarrayOf) extends TypeCoder {
  val itemtype = CodeGen.toCodeable(defn.vltype).typename

  def typename = s"Seq[${itemtype}]"
  def toCode = ""
}


class EnumCoder(defn: VLenumDefn) extends TypeCoder {
  def typename = defn.name

  def toCode: String = {
    val terms = defn.values.map { term =>
      s"""|  val ${cleanName(term)} = new ${defn.name}Enum {
          |    val term: String = "${term}" }"""
    } . mkString("\n")

    s"""sealed trait ${defn.name}Enum
    |trait ${defn.name}
    |object ${defn.name} extends ${defn.name} {
    ${terms}
    |}
    |""" . stripMargin
  }

  def cleanName(orig: String): String =
    orig.replaceAll("-", "_")
}


class AnyOfCoder(defn: VLanyOf) extends TypeCoder {
  def typename = CodeGen.cleanClassName(defn.name)
  def toCode = s"sealed trait ${typename}\n"
}


class OperatorCoder(defn: VLopDefn) extends TypeCoder {
  def typename = CodeGen.cleanClassName(defn.name)

  val fieldTypes = defn.properties.map { prop =>
    ( prop.name, CodeGen.toCodeable(prop.vltype).typename )
  } . toMap
  val fieldNames = defn.properties.map { prop =>
    ( prop.name, CodeGen.mapReserved.getOrElse(prop.name, prop.name) )
  } . toMap

  def toCode: String = {
    val fields = defn.properties.map { prop =>
      s"    _${fieldNames(prop.name)}: ${fieldTypes(prop.name)}"
    } . mkString(",\n")

    val modifiers = defn.properties.map { prop =>
      val field = fieldNames(prop.name)
      s"  def ${field}(__arg: ${fieldTypes(prop.name)}): ${typename}" +
            s" = this.copy(_${field} = __arg)"
    } . mkString("", "\n", "\n")

    Seq(makeHelperClasses(),
        Some(s"case class ${typename}("),
        if (fields.nonEmpty) Some(s"\n${fields}") else None,
        Some(") {\n"),
        if (modifiers.nonEmpty) Some(modifiers) else None,
        Some("}\n\n")) . flatten . mkString("")
    // FIXME - extract description as scaladoc comment
  }

  def makeHelperClasses(): Option[String] = {
    @tailrec
    def recurse(vltypes: Seq[VLtypeDefn],
                locals: Seq[Option[VLtypeDefn]]): Seq[Option[VLtypeDefn]] = {
      vltypes match {
        case head :: tail => {
          val (loc, children) = head match {
            case enum: VLenumDefn =>  (Some(enum), Nil)
            case ao: VLanyOf =>       (Some(ao), ao.options)
            case arr: VLarrayOf =>    (None, Seq(arr.vltype))
            case _ =>                 (None, Nil)
          }
          recurse(children ++ tail, locals :+ loc)
        }
        case _ => locals
      }
    }
    // FIXME - these need to be extracted to top of file, to allow type aliases

    val locals = recurse(
                  defn.properties.map { prop => prop.vltype }, Nil) . flatten

    // FIXME - insert actual type definition

    if (locals.nonEmpty) {
      Some(locals.map { vltype =>
        s"trait ${CodeGen.toCodeable(vltype).typename}"
        } . mkString("", "\n", "\n\n"))
    } else {
      None
    }
  }
}


class ObjRefCoder(defn: VLobjRef) extends TypeCoder {
  def typename = CodeGen.cleanClassName(defn.alias)
  def targetname = CodeGen.cleanClassName(defn.target.name)
  def toCode = {
    s"""object ${defn.name} {
    |  type ${typename} = ${targetname}
    |}
    |import ${defn.name}._
    |""" . stripMargin
  }
}


class CodeGen(val stream: OutputStream) {
  def apply(schema: VLschema) {
    val pw = new PrintWriter(stream)

    val warning = "/* AUTOGENERATED by VL4S - do not edit by hand */\n"

    pw.print(warning)
    pw.print("\npackage uk.rwpenney.vl4s\n")

    schema.types.foreach { vltype =>
      val codeable = CodeGen.toCodeable(vltype)

      pw.print("\n")
      pw.print(codeable.toCode)
    }

    pw.print("\n" + warning)
    pw.close()
  }
}


object CodeGen {
  def toCodeable(vltype: VLtypeDefn): TypeCoder = {
    vltype match {
      case bare: VLbareType =>  new BareCoder(bare)
      case arr: VLarrayOf =>    new ArrayCoder(arr)
      case enum: VLenumDefn =>  new EnumCoder(enum)
      case ao: VLanyOf =>       new AnyOfCoder(ao)
      case op: VLopDefn =>      new OperatorCoder(op)
      case or: VLobjRef =>      new ObjRefCoder(or)
      case _ =>                 new EmptyCoder
    }
  }

  // Conversion for VL properties which class with Scala reserved words
  val mapReserved = Map(
    "type" -> "vtype"
  )

  val mapBareTypes = Map(
    "any" ->      "Any",      // FIXME - improve decoding
    "boolean" ->  "Boolean",
    "number" ->   "Double",
    "object" ->   "Any",      // FIXME - check appropriateness
    "ref" ->      "Any",      // FIXME - improve decoding
    "string" ->   "String"
  )

  def cleanClassName(orig: String): String =
    orig.map {
      case '<' => '_'
      case '>' => '_'
      case c =>   c
    }
}
